service: testbookshop
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  profile: serverless


  region: eu-west-2


package:
  artifact: target/hello-dev.jar

functions:
  books:
    handler: com.testBook.Handler
    events:
      - http:
          path: books
          method: get

